name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.2
    - name: Restore dependencies
      run: msbuild src/MaterialDesignControls.sln -t:restore -p:RestorePackagesConfig=true
    - name: Build iOS
      run: msbuild src/MaterialDesignControls.iOS/MaterialDesignControls.iOS.csproj -t:Rebuild -p:Configuration=Release
    - name: Build Android
      run: msbuild src/MaterialDesignControls.Android/MaterialDesignControls.Android.csproj -t:Rebuild -p:Configuration=Release
